import { StyleSheet } from 'react-native';
import { COLOURS } from '../../constants';

const CartCss = StyleSheet.create({
    cart: {
        width: '100%',
        height: '100%',
        backgroundColor: COLOURS.white,
        position: 'relative',
    },
    backIcon: {
        fontSize: 22,
        color: COLOURS.backgroundDark,
        padding: 12,
        backgroundColor: COLOURS.backgroundLight,
        borderRadius: 12,
    },
    title: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomWidth: 1,
        borderBottomColor: COLOURS.backgroundLight,
        marginTop: 10,
    },
    order: {
        fontSize: 30,
        color: COLOURS.black,
        fontWeight: '600',
    },
    cartTitile: {
        fontSize: 25,
        color: COLOURS.black,
        fontWeight: '500',
        letterSpacing: 1,
        paddingTop: 20,
        paddingLeft: 16,
        marginBottom: 10,
    },
    delivery: {
        position: 'relative',
        paddingHorizontal: 16,
        marginVertical: 10,
    },
    deliveryText: {
        fontSize: 22,
        color: COLOURS.black,
        fontWeight: '400',
        letterSpacing: 1,
        marginBottom: 20,
    },
    deliverBox: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    boxLeft: {
        flexDirection: 'row',
        width: '80%',
        alignItems: 'center',
    },
    boxLeftWrapper: {
        color: COLOURS.blue,
        backgroundColor: COLOURS.backgroundLight,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        borderRadius: 10,
        marginRight: 18,
    },
    location: {
        fontSize: 20,
        color: COLOURS.black,
        fontWeight: '500',
    },
    phone: {
        fontSize: 18,
        color: COLOURS.black,
        fontWeight: '400',
        lineHeight: 20,
        opacity: 0.5,
    },
    orderInfo: {
        paddingHorizontal: 16,
        marginVertical: 20,
    },
    orderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    subTotal: {
        fontSize: 20,
        fontWeight: '400',
        maxWidth: '80%',
        color: COLOURS.black,
    },
    checkout: {
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    checkoutBtn: {
        width: '85%',
        backgroundColor: COLOURS.black,
        paddingVertical: 10,

        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkoutBtnText: {
        fontSize: 20,
        fontWeight: '500',
        letterSpacing: 1,
        color: COLOURS.white,
        textTransform: 'uppercase',
    },
    cartItem: {
        width: '100%',
        height: 100,
        marginVertical: 6,
        flexDirection: 'row',
        alignItems: 'center',
    },
    cartItemImgWrap: {
        width: '30%',
        height: 100,
        padding: 14,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLOURS.backgroundLight,
        borderRadius: 10,
        marginRight: 22,
    },
    cartItemImg: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    cartItemInfo: {
        flex: 1,
        height: '100%',
        justifyContent: 'space-around',
    },
    cartItemName: {
        fontSize: 18,
        textTransform: 'capitalize',
        maxWidth: '100%',
        color: COLOURS.black,
        fontWeight: '600',
        letterSpacing: 1,
    },
    cartItemPrice: {
        marginTop: 4,
        flexDirection: 'row',
        alignItems: 'center',
    },
    cartItemPriceText: {
        fontSize: 16,
        fontWeight: '500',
        maxWidth: '85%',
        marginRight: 4,
    },
    cartItemQuantity: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 20,
    },
    minus: {
        borderRadius: 100,
        marginRight: 20,
        padding: 4,
        borderWidth: 1,
        borderColor: COLOURS.backgroundMedium,
    },
    plus: {
        borderRadius: 100,
        marginLeft: 20,
        padding: 4,
        borderWidth: 1,
        borderColor: COLOURS.backgroundMedium,
    },
    quantityIcon: {
        fontSize: 16,
        color: COLOURS.backgroundDark,
    },
    delete: {
        fontSize: 22,
        color: COLOURS.white,
        backgroundColor: COLOURS.red,
        padding: 8,
        borderWidth: 1,
        borderColor: COLOURS.red,
        borderRadius: 100,
    },
});

export default CartCss;
