import { StyleSheet } from 'react-native';
import { COLOURS } from '../../constants';

const ProInfoCss = StyleSheet.create({
    proInfo: {
        width: '100%',
        height: '100%',
        backgroundColor: COLOURS.white,
        position: 'relative',
    },
    container: {
        width: '100%',
        backgroundColor: COLOURS.backgroundLight,
        borderBottomRightRadius: 20,
        borderBottomLeftRadius: 20,
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 4,
    },
    backBtn: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: 16,
        paddingLeft: 16,
    },
    backIcon: {
        fontSize: 24,
        color: COLOURS.backgroundDark,
        padding: 12,
        backgroundColor: COLOURS.white,
        borderRadius: 10,
    },
    navigationSlider: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
        marginTop: 32,
    },
    navigationBar: {
        width: '16%',
        height: 4,
        backgroundColor: COLOURS.black,
        marginHorizontal: 4,
        borderRadius: 150,
    },
    shopping: {
        paddingHorizontal: 16,
        marginTop: 6,
    },
    shoppingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 14,
    },
    shoppngIcon: {
        fontSize: 30,
        color: COLOURS.blue,
        marginRight: 6,
    },
    shoppingText: {
        fontSize: 20,
        color: COLOURS.black,
    },
    detail: {
        flexDirection: 'row',
        marginVertical: 4,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    proName: {
        fontSize: 24,
        fontWeight: '600',
        letterSpacing: 0.5,
        marginVertical: 4,
        color: COLOURS.black,
        maxWidth: '84%',
    },
    linkIcon: {
        fontSize: 24,
        color: COLOURS.blue,
        backgroundColor: COLOURS.blue + 10,
        padding: 8,
        borderRadius: 100,
    },
    proDesc: {
        fontSize: 18,
        color: COLOURS.black,
        fontWeight: '400',
        letterSpacing: 1,
        opacity: 0.5,
        lineHeight: 20,
        maxWidth: '85%',
        marginBottom: 18,
    },
    addToCart: {
        alignSelf: 'center',
        width: '90%',
        height: 50,
        backgroundColor: COLOURS.black,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: 20,
    },
    addToCartText: {
        fontSize: 18,
        fontWeight: '500',
        letterSpacing: 1,
        color: COLOURS.white,
        textTransform: 'uppercase',
    },
    price: {
        fontSize: 30,
        fontWeight: '500',
        maxWidth: '85%',
        color: COLOURS.black,
        marginBottom: 4,
    },
    location: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginVertical: 14,
        borderBottomColor: COLOURS.backgroundLight,
        borderBottomWidth: 1,
        paddingBottom: 20,
    },
    locationRow: {
        flexDirection: 'row',
        width: '80%',
        alignItems: 'center',
    },
    locationWrap: {
        color: COLOURS.blue,
        backgroundColor: COLOURS.backgroundLight,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        borderRadius: 100,
        marginRight: 10,
    },
    locationIcon: {
        fontSize: 25,
        color: COLOURS.blue,
    },
    locationText: {
        fontSize: 20,
    },
});

export default ProInfoCss;
